version: '3.5'

services:
  postgres:
    container_name: hackathon_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-hackathon_dev}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

  pgadmin:
    container_name: hackathon_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin4/storage
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped
  
  hackathon_app:
    restart: unless-stopped
    container_name: hackathon_app
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
      - '3000:3000'